### ISSUE TITLE
Sprint Focus: Jupyter Notebooks week 6 of 6

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#108]
## Sprint Theme

Testing and documentation, communication

## Goals for the Sprint
* [ ] #110 
   * [x] Verify each repo and package, license, setup.py, metadata clean-up
   * [x] custom script to build all packages, all platforms as a workaround for the official build system
   * [ ] Wrap up builds: see #111 Windows Builds, Linux-32 - go thru binstar.yaml files and make sure they're all building for all the supported configuration
* [ ] #109 Manually testing single-extension, single package environments on all platforms and (supported) Python versions, test some (all) of the new extensions against new Jupyter 4.1
* [ ] #70 - fix upstream issue in order to address BG concerns (hopefully released in 4.2 at some point in future)
* [x] Create PyPI packages for nbSetupTools (as-is) (sizing: 1-2)
* [ ] #50 - extend anaconda upload functionality
* [ ] [PAUSED] Plan for what happens next
   * [ ] How do we communicate CIO, CIO Sales, Jupyter team, Jupyter extension builders, broader community
   * [ ] strategy for Jupyter 5 and conda as the package manager of choice
* [ ] Planning for hosted notebooks (ongoing)
* [ ] [NEW] NB Extensions planning with Jupyter team

## Stretch Goals
* [ ] convert nbPresent to use nbsetuptools 
* [x] #86 improved kernel selection mechanism
* [ ] Casper.JS headless browser test of nbpresent working (future: integrate into nbSetup)

## Defer to future sprints
* [ ] Test all extensions against 4.1 release of jupyter

## Retro Points
* [ ] get feedback to repo & distribution team about gaps in build system
* [ ] be more thorough as reviewer or tester to avoid additional cycles

Prior Sprint Goals - #94
