### ISSUE TITLE
Sprint Focus: Jupyter Notebook Extensions Week 8

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#126]
## Sprint Goals
* [x] Dependency: conda package of jupyter notebook 4.1 
* [ ] Jupyter 4.2 in 4 weeks or less - incorporates new canonical extension approach - review PR to understand how we might adapt our existing extensions to take advantage of that 
* [ ] Diff - draft end-user requirements (use it on NBViewer? ) - input from @bollwyvl , @damianavila @ijstokes @chdoig , others?
* [ ] Summarize PandW, DirSvcs impact on notebooks to rest of the team ( @ijstokes or @bollwyvl ) 
* [x] Feedback on Anaconda Upload GUI PR for Nick
* [ ] #128 - Add tests to nb-AnacondaCloud
* [ ] work on getting testing going: smoke test on Win64, python2&pytyon3
* [x] question - Win10 vs. Win7
* [ ] Discuss: use nb-present at next quarterly meeting
* [ ] Roadmap - MIP Goal: "Theming for Static Export" - establish clear definition (discuss with @pzwang and @ijstokes, @bollwyvl and @damianavila  ) - see anaconda-server/nbpresent#34 for some additional thoughts and discussion

## stretch goals
* [ ] Modify nb-AnacondaCloud upload approach so it's not blocking your UI

Note: Previous Sprint #118 

## Deferred
* [ ] Build 4.1 notebook and put into our channel (until Conda releases official one)
* [ ] Diff - technical plan
* [ ] Automated builds using Anaconda-Build system (see issue #111 )
* [ ] Themeing for presentations 

## Discuss of Diff
- nbDime more focused on the low-level data model for merges - may be different than our concern/focus; establish common language for diff; 
- NB Diff - provide visual diff for notebooks - high-level, similar to what we're focussed on; flask app (helpful for integration with A-Cloud); but not touched since June, very old, ipython 2.x
- both offer merge functionality
- our focus: not so much merge, but being clear on differences, provenance, e.g. image diffs on bokeh canvas; 
- questions: is this an extension, stand-alone app, server-less JS?

**Comment by stephenakearns** [comment]
re: Win 10 vs. Win 7, we are about even in terms of download traffic (41% Win 7 vs. 37% Win 10) - we should focus on Windows 10

**Comment by stephenakearns** [comment]
Wednesday: @damianavila working on reviewing the AnacondaCloud upload PR and adapting extensions to 4.2. 4.2 expected in 4 weeks or less (jupyter meeting update). Release Decision: Stick with the plan to launch with 4.2. @bollwyvl working on getting Win7 image running (painful - 7+rounds of windows update to the image to get it running). working on windows testing and also NBPresent updates. Idea: have regularly built vagrant windows boxes that are patched and ready to go. Steve: plant seed around using NBPresent for next Quarterly meeting. 

@ijstokes ask @bollwyvl to demo some neat visual diff thinking: 
![image](https://cloud.githubusercontent.com/assets/13372164/12297634/b296f966-b9d3-11e5-8bb6-084105a5e33e.png)

**Comment by stephenakearns** [comment]
### Daily Stand-up
@damianavila  Merging PRs; helping Mike with getting extenisons into wakari; rebuild packages to upload to anaconda.org b/c current ones are out of date (work with 4.1 jupyter notebook); change build process to upload to dev instead of main;  explore 4.2 extensions approach; 

@bollwyvl  finishing up troubleshooting issues on nb-present server-side generation; wanting to generate a pure, archival quality HTML presentation (avoid having to use bokeh CDN); side project off the clock: integrated diff thinking into nb-viewer; scrolling sync'd; 

Steve - confirm roadmap definition; see diff requriements discussion;

**Comment by stephenakearns** [comment]
Nick: PR against anaconda-server/nb-anacondacloud#8 - discovered testing framework changed in jupyter notebook 4.1 (from 4.0.6); work on adding tests to nb-anacondacloud; 

Damian: migrate to new namespace in Anaconda Cloud (from Anaconda Notebooks to Anaconda-nb-extensions); testing extensions on Linux and Jupyter 4.1

Steve: add anaconda-nb-extensions org to the continuum queue
