### ISSUE TITLE
Epic: Anaconda Notebook Extensions for Jupyter (Phase 1)

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#32]
_From @stephenakearns on November 6, 2015 18:48_

Please also refer to project brief: 
https://docs.google.com/document/d/1zEsCYzZ0SbQYPYZ9xTv1faErrN5nMB1JvRFAbnhjQfM/edit#

*  [x] Pre-requisites to start working on Jupyter Extensions (11 Points)
   * [x] Prep existing GitHub repo anaconda-notebook
      * [x] https://github.com/ContinuumIO/anaconda-notebook
      * [x] Merge existing PR (Damian) https://github.com/ContinuumIO/anaconda-notebook/pull/14 (1story point)
      * [x] Migrate repo to Anaconda organization (1 point)
      * [x] Create basic conda package with these (1 point)
   * [x] Create skeleton conda recipe for a single extension. (2 points)
https://github.com/Anaconda-Server/anaconda-notebook/issues/19
   * [x] Prototype server extension (2 story points)
https://github.com/Anaconda-Server/anaconda-notebook/issues/18
   * [x] Wireframes for all phase 1 proposed extensions - Ian (2 story points)
https://github.com/Anaconda-Server/anaconda-notebook/issues/22
   * [x] Complete Wakari PRs to split extensions into independent extensions
      * https://github.com/ContinuumIO/wakari-app-ipython/pull/38 (1story point)
      * https://github.com/ContinuumIO/wakari-app-ipython/pull/39 (1story point)
	
* [ ] Initial adoption is through Anaconda Toolkit Jupyter extensions that push and pull local content from Anaconda Enterprise (25 points)
    * [ ] Notebook-based: (18 story points)
        * [x] Vanilla Conda Environments menu 5 points #45
            Idea: from inside a notebook, change which conda environment is in use. Has implications for available kernels. This probably includes a combination of new menu item “Conda” and new dropdown “kernels” or *possibly* hijack the kernel dropdown.
             * [x] select (from available list) (conda info -a)
             * [x] create (conda create -n foo pkg1=ver1 pkg2=ver2)
             * [x] clone (conda create --clone)
             * [x] fetch* (conda env create jsmith/fancyenv)
             * [ ] publish* (conda env upload)
        * [x] Conda pkg ops menu 5 points #46
             Idea: basic conda package operations accessible from notebook, operate on “current” environment for notebook.
             * [x] install (conda install pkg)
             * [x] update (conda update pkg)
             * [x] remove (conda remove pkg)
             * [x] search (conda search, anaconda search)
                  this could be tricky: how to sensibly present results?
             * [ ] info/list (conda info)
                 may not need this: information may be available by some other means
        * [ ] Anaconda Repository menu 8 points #47
              Idea: Notebook-centric operations related to Notebook publishing/sharing on Anaconda 
             * [ ] publish (anaconda notebook upload)
             * [ ] version (not sure this is currently possible)
             * [ ] meta-data (defer: not sure exactly what this would mean, or what Anaconda Server would support)
             * [ ] dependencies (could defer: this is capturing environment or specific package requirements and somehow associating or embedding in notebook meta-data)
             * [ ] ACL (who can read this published notebook?) -- This requires some careful thought since ACLs are at the “abstract” notebook level (all notebook versions within a particular channel/name pair), and are stored on the server. At a minimum, ability to set “public” or “private” (in fact, “force” this setting for all notebook versions). More advanced will need to poll server to find out current settings and sensibly present options.
    * [ ] Jupyter “file browser” view: (15 story points)
         * [x] Conda tab 3 points #48 
Idea: new tab in Jupyter browser view for “Conda” with list of environments and mechanism to perform operations on environments:
             * [x] create (conda create)
             * [x] delete (conda env remove)
             * [x] clone (conda clone)
             * [x] export* (~~conda env upload~~conda list -e)
             * [x] all “in-environment” operations at package level (from above): install, update, remove. How this is done in terms of user flow and UI/UX elements needs some consideration from someone who can advise on this.
    * [ ] Launch notebook in specific conda environment (specified inside notebook meta-data: local env name; inline pkg deps; remote env spec) (8 story points) #49
         * [ ] “just do it” if env already exists
         * [ ] prompt if new env needs to be created
         * [ ] possible cross-platform challenges
    * [ ] Remote information 4 points #50 
         * [ ] Anaconda Enterprise connection
         * [ ] New tab to present this information
* [ ] Search migration from Wakari to Anaconda Repository (8 story points)
    * [ ] Refer to Anaconda-Server/Anaconda-Server#946 - Search Migration
    * [ ] Discuss what this would look like for Phase 1, create story, assign estimate, add to milestone

_Copied from original issue: Anaconda-Server/anaconda-server#936_
